version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-unit-tests:
    macos:
      xcode: "15.0.0"  # Replace with the version of Xcode you're using
    steps:
      - checkout
      - run: 
          name: Install CocoaPods dependencies
          command: pod install
      - run:
          name: Run Unit Tests
          command: xcodebuild -scheme ToDo -workspace ToDo.xcodeproj/project.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' test

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - run-unit-tests
