version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-tests:
    macos:
      xcode: "15.0.0"
    steps:
      - checkout
      - run: 
          name: Resolve Swift Package Manager dependencies
          command: xcodebuild -resolvePackageDependencies -scheme ToDo -workspace ToDo.xcodeproj/project.xcworkspace
      - run:
          name: Run Unit and UI Tests
          command: xcodebuild test -scheme ToDo -workspace ToDo.xcodeproj/project.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4'

workflows:
  build-and-test:
    jobs:
      - say-hello
      - run-tests
